# Numpy Library Course & Practice

# I.) Array creation with arithmetic operation, and some special operation              methods.

In [1]:
import numpy as np

In [2]:
a1 = np.matrix([['a','b','c'],['d','e','f'],['g','h','i']])
print('Initialize matrix :')
print(a1)

Initialize matrix :
[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]


In [3]:
print('After transpose on matrix :')
print(a1.transpose())
print('the number of dimensioin of a1 is : ',a1.ndim)
print('the number of shape of a1 is : ',a1.shape)
print('the datatype of a1 is :',a1.dtype)
print('size of a1 is :',a1.itemsize)
print('the total size is :',a1.nbytes)

After transpose on matrix :
[['a' 'd' 'g']
 ['b' 'e' 'h']
 ['c' 'f' 'i']]
the number of dimensioin of a1 is :  2
the number of shape of a1 is :  (3, 3)
the datatype of a1 is : <U1
size of a1 is : 4
the total size is : 36


In [4]:
a2 = np.matrix([['d','a','e'],['a','t','w'],['s','e','y']])
print('Initialize Matrix :')
print(a2)
print('After traspose :')
print(a2.T)
print('the number of dimensioin of a2 is : ',a2.ndim)
print('the number of shape of a2 is : ',a2.shape)
print('the datatype of a1 is :',a2.dtype)
print('size of a2 is :',a2.itemsize)
print('the total size of a2 is :',a2.nbytes)

Initialize Matrix :
[['d' 'a' 'e']
 ['a' 't' 'w']
 ['s' 'e' 'y']]
After traspose :
[['d' 'a' 's']
 ['a' 't' 'e']
 ['e' 'w' 'y']]
the number of dimensioin of a2 is :  2
the number of shape of a2 is :  (3, 3)
the datatype of a1 is : <U1
size of a2 is : 4
the total size of a2 is : 36


In [5]:
b = np.array([[1,2],[4,6]])
print('first matrix :')
print(b)

c = np.array([[7,-5],[8,0]])
print('Second Matrix :')
print(c)

print('determinant of b is such that :',np.linalg.det(b))
print('determinant of c is such that :',np.linalg.det(c))
print('the number of dimensioin of b and c are : ',b.ndim,'',c.ndim)
print('the number of shape of b and c are : ',b.shape,'',c.shape)
print('the datatype of b is :',b.dtype)
print('the datatype of c is :',c.dtype)
print('size of b is :',b.itemsize)
print('the total size of b is :',b.nbytes)

first matrix :
[[1 2]
 [4 6]]
Second Matrix :
[[ 7 -5]
 [ 8  0]]
determinant of b is such that : -2.0
determinant of c is such that : 39.99999999999998
the number of dimensioin of b and c are :  2  2
the number of shape of b and c are :  (2, 2)  (2, 2)
the datatype of b is : int32
the datatype of c is : int32
size of b is : 4
the total size of b is : 16


In [6]:
x = c+b
print('After summation :')
print(x)

y = c*b
print('After multiplication :')
print(y)

z = c**2
print('Square of c is :')
print(z)
# w = a1+a2
# print('Summation between a1 and a2 is :')
# print(w)  # we cannot print it because no mathematical operation on character or string.
print('the number of dimensioin of c*b is : ',y.ndim)
print('the shape of b and c are :',c.shape)
print('the datatype of c is :',c.dtype)
print('size of a1 is :',x.itemsize)
print('the total size is :',x.nbytes)

After summation :
[[ 8 -3]
 [12  6]]
After multiplication :
[[  7 -10]
 [ 32   0]]
Square of c is :
[[49 25]
 [64  0]]
the number of dimensioin of c*b is :  2
the shape of b and c are : (2, 2)
the datatype of c is : int32
size of a1 is : 4
the total size is : 16


In [33]:
d = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
e = np.array([[1,2,3,4,5,0],[-3,8,-5,0,8,8],[1,2,3,4,5,6]])
print('The 2x3 order of matrix is :\n',d)
print('The 3x6 order of matrix is :\n',e)

a11 = int(input('Enter a11: '))
a12 = int(input('Enter a12: '))
a13 = int(input('Enter a13: '))
a14 = int(input('Enter a14: '))

a21 = int(input('Enter a21: '))
a22 = int(input('Enter a22: '))
a23 = int(input('Enter a23: '))
a24 = int(input('Enter a24: '))

a31 = int(input('Enter a31: '))
a32 = int(input('Enter a32: '))
a33 = int(input('Enter a33: '))
a34 = int(input('Enter a34: '))

a41 = int(input('Enter a41: '))
a42 = int(input('Enter a42: '))
a43 = int(input('Enter a43: '))
a44 = int(input('Enter a44: '))

f = np.array([[a11,a12,a13,a14],[a21,a22,a23,a24],[a31,a32,a33,a34],[a41,a42,a43,a44]])
print('The square matrix ordered 4 is such that :')
print(f)
print('the number of dimensioin of f is : ',f.ndim)
print('the number of shape of f is : ',f.shape)
print('the datatype of f is :',f.dtype)
print('size of element of f is :',f.itemsize)
print('the total size of f is :',f.nbytes)

The 2x3 order of matrix is :
 [[9. 8. 7.]
 [6. 5. 4.]]
The 3x6 order of matrix is :
 [[ 1  2  3  4  5  0]
 [-3  8 -5  0  8  8]
 [ 1  2  3  4  5  6]]
Enter a11: 1
Enter a12: 2
Enter a13: 3
Enter a14: 4
Enter a21: 5
Enter a22: 6
Enter a23: 7
Enter a24: 5
Enter a31: 34
Enter a32: 5
Enter a33: 3
Enter a34: 5
Enter a41: 3
Enter a42: 5
Enter a43: 3
Enter a44: 54
The square matrix ordered 4 is such that :
[[ 1  2  3  4]
 [ 5  6  7  5]
 [34  5  3  5]
 [ 3  5  3 54]]
the number of dimensioin of f is :  2
the number of shape of f is :  (4, 4)
the datatype of f is : int32
size of element of f is : 4
the total size of f is : 64


In [34]:
### g = np.matrix([[1,2,3,4,5],[6,7,8,9,0],[-1,-3,4,5,6],[2,3,4,5,6],[0,8,6,5,4]])
print('+ matrix g before operation :')
print(g)
print('+ square root of g is such that :')
print(g**1/2)
print('+ square of g is such that :')
print(g**2)
print('+ cube root of g is such that :')
print(g**1/3)
print('+ cube of g is such that :')
print(g**3)
print('+ determinant of g is :',np.linalg.det(g))
print('+ determinant of g transposition is :',np.linalg.det(g.T))
print('+ determinant of square of g is :',np.linalg.det(g**2))
print('+ determinant of cube root of g is :',np.linalg.det(g**1/3))
print('+ determinant of g power 3 is :',np.linalg.det(g**3))
print('+ the number of dimensioin of g is : ',g.ndim)
print('+ the number of shape of g is : ',g.shape)
print('+ the datatype of g is :',g.dtype)
print('+ size of element g is :',g.itemsize)
print('+ size of g is :',g.size)
print('+ the total size of g is :',g.nbytes)
# if we want to get the output like this unless we click shift + o or go to cell -> Current Output-> Toggle Scrolling

+ matrix g before operation :
[[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5]
 [ 1  2  3  4  5  6  7  2  3  4  5  6  8  9  0]
 [ 4  6  3  2  1 -9 -7  0  6  4  0  0  1 -2  3]
 [ 4  1  5  5  6  0 -4 -2 -1  6  6  7  8  9  0]]
+ square root of g is such that :
[[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   0.5  1.   1.5  2.
   2.5]
 [ 0.5  1.   1.5  2.   2.5  3.   3.5  1.   1.5  2.   2.5  3.   4.   4.5
   0. ]
 [ 2.   3.   1.5  1.   0.5 -4.5 -3.5  0.   3.   2.   0.   0.   0.5 -1.
   1.5]
 [ 2.   0.5  2.5  2.5  3.   0.  -2.  -1.  -0.5  3.   3.   3.5  4.   4.5
   0. ]]
+ square of g is such that :
[[  1   4   9  16  25  36  49  64  81 100   1   4   9  16  25]
 [  1   4   9  16  25  36  49   4   9  16  25  36  64  81   0]
 [ 16  36   9   4   1  81  49   0  36  16   0   0   1   4   9]
 [ 16   1  25  25  36   0  16   4   1  36  36  49  64  81   0]]
+ cube root of g is such that :
[[ 0.33333333  0.66666667  1.          1.33333333  1.66666667  2.
   2.33333333  2.66666667  3.          3.333

LinAlgError: Last 2 dimensions of the array must be square

In [35]:
h = np.array([[1,2,3,4,5,6,7,8,9,10],[4,1,5,5,6,0,-4,-2,-1,6],[1,8,0,7,8,9,-2,-1,3,-4],[2,4,5,6,4,3,8,9,0,7],
              [3,8,9,0,4,3,5,6,7,8],[1,2,3,4,5,6,7,8,9,0],[4,6,3,2,1,-9,-7,0,6,4],[1,4,5,6,7,5,4,3,2,1],
              [1,2,3,4,5,6,7,8,9,0],[0,0,7,0,5,4,3,9,0,1]])
print('Matrix h before operation :')
print(h)

i = np.array([[1],[2],[1],[3],[5],[2],[0],[7],[-1],[-2]])
print('Matrix i before operation :')
print(i)

print('Square root of h is such that :')
print(h**1/2)

print('Square of h is such that :')
print(h**2)

print('Determinant of h is such that :',np.linalg.det(h))
print('Determinant of h transposition is such that :',np.linalg.det(h.T))

print('After multiplication i and h is such that :')
print(i*h)
print('Determinant of i*h is such that :',np.linalg.det(i*h))
print('+ the number of dimensioin of h is : ',h.ndim)
print('+ the number of shape of h is : ',h.shape)
print('the datatype of h is :',h.dtype)
print('size of of element of h is :',h.itemsize)
print('the total size of h is :',h.nbytes)

Matrix h before operation :
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 4  1  5  5  6  0 -4 -2 -1  6]
 [ 1  8  0  7  8  9 -2 -1  3 -4]
 [ 2  4  5  6  4  3  8  9  0  7]
 [ 3  8  9  0  4  3  5  6  7  8]
 [ 1  2  3  4  5  6  7  8  9  0]
 [ 4  6  3  2  1 -9 -7  0  6  4]
 [ 1  4  5  6  7  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  8  9  0]
 [ 0  0  7  0  5  4  3  9  0  1]]
Matrix i before operation :
[[ 1]
 [ 2]
 [ 1]
 [ 3]
 [ 5]
 [ 2]
 [ 0]
 [ 7]
 [-1]
 [-2]]
Square root of h is such that :
[[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5. ]
 [ 2.   0.5  2.5  2.5  3.   0.  -2.  -1.  -0.5  3. ]
 [ 0.5  4.   0.   3.5  4.   4.5 -1.  -0.5  1.5 -2. ]
 [ 1.   2.   2.5  3.   2.   1.5  4.   4.5  0.   3.5]
 [ 1.5  4.   4.5  0.   2.   1.5  2.5  3.   3.5  4. ]
 [ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  0. ]
 [ 2.   3.   1.5  1.   0.5 -4.5 -3.5  0.   3.   2. ]
 [ 0.5  2.   2.5  3.   3.5  2.5  2.   1.5  1.   0.5]
 [ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  0. ]
 [ 0.   0.   3.5  0.   2.5  2.   1.5  4.5  

In [36]:
j = np.matrix([['a','b','c','d','e'],['f','g','h','i','j'],['k','l','m','n','o'],['p','q','r','s','t'],['u','v','w','x','y']])
print('Initialize matrix :')
print(j)
print('After transposition :')
# k = j.transpose()    # k = j.transpose() or k=j.T are the same operation on matrix.
print(j.T)
print('the datatype of j is :',j.dtype)
print('size of element of j is :',j.itemsize)
print('the total size is :',j.nbytes)

Initialize matrix :
[['a' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']
 ['k' 'l' 'm' 'n' 'o']
 ['p' 'q' 'r' 's' 't']
 ['u' 'v' 'w' 'x' 'y']]
After transposition :
[['a' 'f' 'k' 'p' 'u']
 ['b' 'g' 'l' 'q' 'v']
 ['c' 'h' 'm' 'r' 'w']
 ['d' 'i' 'n' 's' 'x']
 ['e' 'j' 'o' 't' 'y']]
the datatype of j is : <U1
size of element of j is : 4
the total size is : 100


In [37]:
k = np.array([[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5],[4,1,5,5,6,0,-4,-2,-1,6,6,7,8,9,0],[1,8,0,7,8,9,-2,-1,3,-4,-8,-1,2,3,4],
              [2,4,5,6,4,3,8,9,0,7,2,3,4,5,6],[3,8,9,0,4,3,5,6,7,8,0,0,1,2,3],[1,2,3,4,5,6,7,2,3,4,5,6,8,9,0],
              [4,6,3,2,1,-9,-7,0,6,4,0,0,1,-2,3],[1,4,5,6,7,5,4,3,2,1,1,2,0,0,4],[1,2,3,4,5,6,7,8,9,0,9,9,5,4,8],
              [2,3,4,5,6,7,8,9,0,1,2,4,3,4,5],[0,0,7,0,5,4,3,9,0,1,0,0,8,-9,-2],[1,2,3,4,5,6,7,8,9,0,0,9,8,4,3],
              [1,2,3,4,5,6,7,8,9,0,9,7,5,4,3],[1,2,3,4,6,-9,-8,-6,-3,-1,2,3,5,6,7],[0,0,2,1,3,4,5,6,7,8,6,5,4,9,6]])
print('=> Before operation :')
print(k)
print('=> Transposition of k is such that :')
print(k.T)
print('=> Determinant of k is : ',np.linalg.det(k))
print('=> Number of Dimension is :',k.ndim)
print('=> Shape of k is :',k.shape)
print('=> Data type of k is :',k.dtype)
print('=> Size of k is :',k.size)

=> Before operation :
[[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5]
 [ 4  1  5  5  6  0 -4 -2 -1  6  6  7  8  9  0]
 [ 1  8  0  7  8  9 -2 -1  3 -4 -8 -1  2  3  4]
 [ 2  4  5  6  4  3  8  9  0  7  2  3  4  5  6]
 [ 3  8  9  0  4  3  5  6  7  8  0  0  1  2  3]
 [ 1  2  3  4  5  6  7  2  3  4  5  6  8  9  0]
 [ 4  6  3  2  1 -9 -7  0  6  4  0  0  1 -2  3]
 [ 1  4  5  6  7  5  4  3  2  1  1  2  0  0  4]
 [ 1  2  3  4  5  6  7  8  9  0  9  9  5  4  8]
 [ 2  3  4  5  6  7  8  9  0  1  2  4  3  4  5]
 [ 0  0  7  0  5  4  3  9  0  1  0  0  8 -9 -2]
 [ 1  2  3  4  5  6  7  8  9  0  0  9  8  4  3]
 [ 1  2  3  4  5  6  7  8  9  0  9  7  5  4  3]
 [ 1  2  3  4  6 -9 -8 -6 -3 -1  2  3  5  6  7]
 [ 0  0  2  1  3  4  5  6  7  8  6  5  4  9  6]]
=> Transposition of k is such that :
[[ 1  4  1  2  3  1  4  1  1  2  0  1  1  1  0]
 [ 2  1  8  4  8  2  6  4  2  3  0  2  2  2  0]
 [ 3  5  0  5  9  3  3  5  3  4  7  3  3  3  2]
 [ 4  5  7  6  0  4  2  6  4  5  0  4  4  4  1]
 [ 5  6  8  4  4  5  1  7  5

# II.) Accessing and Changing specific elements, row and columns in matrix

In [38]:
a = np.matrix([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[2,4,7,8,9,6,4],[0,9,0,7,5,4,3]])
print('=> Iniitialize matrix :\n'+str(a))

# Get specific element[r,c]
print('=> Specific element[row,column] :')
print('\t\t\t\ta06 =',a[0,6]) # row(index[0]) and column(index[6])
print('\t\t\t\ta10 =',a[1,0])
print('\t\t\t\ta15 =',a[1,5])
print('\t\t\t\ta03 =',a[0,3])

# Get a specific row and column
print('=> Specific row :')
print('\t+ 0th row :',a[0,:])
print('\t+ 3st row :',a[3,:])
print('\t+ 2st row :',a[2,:])

print('=> Specific column :')
print('+ 0th column :\n'+str(a[:,0]))
print('+ 2th column :\n'+str(a[:,2]))
print('+ 4th column :\n'+str(a[:,4]))


=> Iniitialize matrix :
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [ 2  4  7  8  9  6  4]
 [ 0  9  0  7  5  4  3]]
=> Specific element[row,column] :
				a06 = 7
				a10 = 8
				a15 = 13
				a03 = 4
=> Specific row :
	+ 0th row : [[1 2 3 4 5 6 7]]
	+ 3st row : [[0 9 0 7 5 4 3]]
	+ 2st row : [[2 4 7 8 9 6 4]]
=> Specific column :
+ 0th column :
[[1]
 [8]
 [2]
 [0]]
+ 2th column :
[[ 3]
 [10]
 [ 7]
 [ 0]]
+ 4th column :
[[ 5]
 [12]
 [ 9]
 [ 5]]


In [39]:
# Get little more fancy [row-th order,startindex:endindex:stepsize] where stepsize is a step of order forward.
print('the fancy location of matrix a is such that :')
print(a[0,1:6:2])
print(a[1,0:6:1])
print(a[3,3:6:1])
print(a[2,2:-1:1])

the fancy location of matrix a is such that :
[[2 4 6]]
[[ 8  9 10 11 12 13]]
[[7 5 4]]
[[7 8 9 6]]


In [40]:
b = np.matrix([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print('=> Initialize matrix:\n'+str(b))
b[1,5] = 20
print('=> After change value at 1st row and 5th column:\n'+str(b))
b[:,2] = 5
print('=> After change value at 2nd column:\n'+str(b))

=> Initialize matrix:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
=> After change value at 1st row and 5th column:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
=> After change value at 2nd column:
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [41]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
# Get specific element(work outside in)
print('+ element stay at 1st row and 1st column of first matrix :'+str(c[0,1,1]))  # c[order of matrix,row-th,column-th]
print('+ element stay at 1st row of these two matrices :\n'+str(c[:,1,:]))
print('+ element stay at 0th row and 1st-column of these two matrices :\n'+str(c[:,0,1]))
c[:,1,:] = [[9,9],[8,8]]
print('+ element stay at 1st row of these two matrix after change value :\n'+str(c))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
+ element stay at 1st row and 1st column of first matrix :4
+ element stay at 1st row of these two matrices :
[[3 4]
 [7 8]]
+ element stay at 0th row and 1st-column of these two matrices :
[2 6]
+ element stay at 1st row of these two matrix after change value :
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# III.) Initialize different types of array or matrix

# a.) Zero Matrix:

In [42]:
d = np.zeros(5)  # 1 row and 5 columns
print('=> zero matrix has 1 row and 5 columns :\n'+str(d))
print("\n",end='')

e = np.zeros((4,6)) # 4 rows and 6 columns
print('=> zero matrix has 4 rows and 6 columns :\n'+str(e))

f = np.zeros((3,5,7))
print('\n=> 3 zero matrices that each has 5 rows and 7 columns :\n'+str(f))

g = np.zeros((3,5,7,3))
print('\n=> 15 = 3*5 zero matrices that each has 7 rows and 3 columns :\n'+str(g))

h = np.zeros((4,5,7,3))
print('\n=> 20 = 4*5 zero matrices that each has 7 rows and 3 columns :\n'+str(h))

=> zero matrix has 1 row and 5 columns :
[0. 0. 0. 0. 0.]

=> zero matrix has 4 rows and 6 columns :
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

=> 3 zero matrices that each has 5 rows and 7 columns :
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]

=> 15 = 3*5 zero matrices that each has 7 rows and 3 columns :
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.

# b.) One Matrix

In [43]:
d = np.ones((2,3))
print('first array :')
print(d)

print('\nsecond array :')
e = np.ones((2,3,5))
print(e)

print('\nthird array :')
f = np.ones((4,6,10))
print(f)

print('\nfourth array :')
g = np.ones((10,10,10))
print(g)

print('\nfift array :')
h = np.ones((4,2,2),dtype = 'int32')
print(h)
print('data type of h is :',h.dtype)

first array :
[[1. 1. 1.]
 [1. 1. 1.]]

second array :
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

third array :
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 

# C.) Any other number of matrix

In [44]:
x = np.full((2,2),99,dtype='float32')
print('first full array :\n'+str(x))
y = np.full((10,10,10),3)
print('second full array :\n'+str(y))

first full array :
[[99. 99.]
 [99. 99.]]
second full array :
[[[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3

In [45]:
m = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[0,9,0,8,6,5,-3]])
print(np.full_like(m,4))
print('\n',end='')
print(np.full(m.shape,4))
print(np.full_like(m,5))
# np.full_like(m,a) = np.full(m.shape,a) , where a is a constant

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]


# D.) Random Number on Matrix

In [46]:
print('==> first random :\n'+str(np.random.rand(4,2)))
print('\n==> second random :\n'+str(np.random.rand(4,2,3)))
print('\n==> third random :\n'+str(np.random.random_sample(m.shape)))
print('\n==> fourth random :\n'+str(np.random.randint(-4,8,size=(3,3,3))))
print('\n==> second random :\n'+str(np.random.randint(4,100,size=(3,4,5)))) 
# np.random.rand(number of matrix,row-th,column-th), if no input number of matrix it will display just a matrix default.
# np.random.random_sample(m.shape) : this case we need input m.shape such the form (a,b) where a,b are row-th and column-th respectively in order.
# np.random.randint(startValue,endValue,size(#matrix,row-th,column-th))

==> first random :
[[0.13141311 0.04752581]
 [0.90008397 0.072313  ]
 [0.1018948  0.67550365]
 [0.78977683 0.64931087]]

==> second random :
[[[0.19820321 0.99782074 0.91302252]
  [0.00281243 0.31942854 0.85906474]]

 [[0.14417491 0.51319902 0.90305211]
  [0.74749026 0.58168004 0.58175011]]

 [[0.58317549 0.98392995 0.44615883]
  [0.07770696 0.2546474  0.49967248]]

 [[0.04993752 0.93576439 0.04876434]
  [0.86060534 0.04698223 0.47566344]]]

==> third random :
[[0.0886776  0.26351274 0.28510269 0.1968524  0.38392274 0.99901907
  0.54509117]
 [0.42757124 0.76102302 0.96516881 0.27280553 0.2185551  0.7390187
  0.26611123]
 [0.55498355 0.97985059 0.72434724 0.67537062 0.29224244 0.56575488
  0.26739267]]

==> fourth random :
[[[-2  2 -3]
  [ 1  6  4]
  [ 4  2 -3]]

 [[ 0 -1 -2]
  [-1 -4  4]
  [ 4  0  6]]

 [[-4  2 -3]
  [ 3 -1 -3]
  [ 0  3  1]]]

==> second random :
[[[19 74 77 94 47]
  [78 81 80 52 75]
  [41 97 93 55 98]
  [51 17 47 49 29]]

 [[59 35 96 76 85]
  [53 68 51 81  9]
  [55 16

# E.) Identity Matrix 

In [47]:
print('==> 3rd order of identity matrix :')
print(np.identity(3))

print('\n==> 7th order of identity matrix :')
print(np.identity(7))

print('\n==> 10th order of identity matrix :')
print(np.identity(10))
print('\n==> after operation :\n'+str(np.identity(10)**2))

print('\n==> 100th order of identity matrix :')
print(np.identity(100))

print('\n==> multiplication between x and identity matrix :')
print(x*np.identity(2))

==> 3rd order of identity matrix :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

==> 7th order of identity matrix :
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]

==> 10th order of identity matrix :
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

==> after operation :
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]



In [48]:
# Repeat an array
matrix = np.array([[1,2,3]])
r = np.repeat(matrix,10,0)  # 0 is default value for the axis where set of axis = {-1,0,1} 
print(r)
print('\n',end='')
r = np.repeat(x,7,0)
print('7 of matrix x is such that :\n'+str(r))
# np.repeat(matrix,#repetition,axis) : it will display the matrix that repeat base on we input.

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]

7 of matrix x is such that :
[[99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]
 [99. 99.]]


In [49]:
table = np.ones((5,5))
print(table)
print('\n',end='')

z = np.zeros((3,3))
z[1,1] = 9
print(z)
print('\n',end='')

table[1:4,1:4] = z
print('after update data :')
print(table)

print('\n')
w = np.identity(4)
v = np.identity(3)
x = np.ones((10,10))
y = np.zeros((8,8))
y[4,4] = 2
x[1:9,1:9] = y
x[1:5,1:5] = w
x[6:9,6:9] = v
print(x)
print('transposition of x is such that :\n'+str(x.T))
print('determinant of x is :',np.linalg.det(x))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

after update data :
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 2. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
transposition of x is such that :
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 2. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
determinant of x is : 0.0


# F.) Copying Array :

In [50]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

print('\n',end='')
b = a.copy()
b[0] = 99
print(a)

print('\n',end='')
print(b)

[100   2   3]

[100   2   3]

[99  2  3]


# IV.) Mathematics

In [51]:
y = np.array([3,4,5,6])
print(y)

print('\n',end='')
y += 2
print(y)

print('\n',end='')
m = y-14
print(m)  # this case the substractable value is equal a-2 that it cut 2 from this. if a<=2 it will display default matrix. 

print('\n',end='')
w = y*2
print(w)

print('\n',end='')
x = y/2
print(x)

[3 4 5 6]

[5 6 7 8]

[-9 -8 -7 -6]

[10 12 14 16]

[2.5 3.  3.5 4. ]


In [52]:
from math import sqrt
a = np.matrix([1,-1,-1/2,1/2,sqrt(2)/2,sqrt(3)/2])
print('+ angle radiant of matrix a compare with cosine is such that :\n',np.arccos(a))
print('+ angle radiant of matrix a compare with sine is such that :\n',np.arcsin(a))
print('+ angle radiant of matrix a compare with tangent is such that :\n',np.arctan(a))
print('+ angle radiant of matrix a compare with cotangent is such that :\n',1/np.arctan(a))

+ angle radiant of matrix a compare with cosine is such that :
 [[0.         3.14159265 2.0943951  1.04719755 0.78539816 0.52359878]]
+ angle radiant of matrix a compare with sine is such that :
 [[ 1.57079633 -1.57079633 -0.52359878  0.52359878  0.78539816  1.04719755]]
+ angle radiant of matrix a compare with tangent is such that :
 [[ 0.78539816 -0.78539816 -0.46364761  0.46364761  0.61547971  0.71372438]]
+ angle radiant of matrix a compare with cotangent is such that :
 [[ 1.27323954 -1.27323954 -2.15681043  2.15681043  1.62474893  1.40110108]]


# V.) Linear Algebra

# a.) Matrix multiplication

In [53]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a)
print('\n')
print(b)
print('After multiplication between a and b is such that:')
result = np.matmul(a,b)
print(result)

[[1. 1. 1.]
 [1. 1. 1.]]


[[2 2]
 [2 2]
 [2 2]]
After multiplication between a and b is such that:
[[6. 6.]
 [6. 6.]]


In [54]:
c = np.array([[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5],[4,1,5,5,6,0,-4,-2,-1,6,6,7,8,9,0],[1,8,0,7,8,9,-2,-1,3,-4,-8,-1,2,3,4],
              [2,4,5,6,4,3,8,9,0,7,2,3,4,5,6],[3,8,9,0,4,3,5,6,7,8,0,0,1,2,3],[1,2,3,4,5,6,7,2,3,4,5,6,8,9,0],
              [4,6,3,2,1,-9,-7,0,6,4,0,0,1,-2,3],[1,4,5,6,7,5,4,3,2,1,1,2,0,0,4],[1,2,3,4,5,6,7,8,9,0,9,9,5,4,8],
              [2,3,4,5,6,7,8,9,0,1,2,4,3,4,5],[0,0,7,0,5,4,3,9,0,1,0,0,8,-9,-2],[1,2,3,4,5,6,7,8,9,0,0,9,8,4,3],
              [1,2,3,4,5,6,7,8,9,0,9,7,5,4,3],[1,2,3,4,6,-9,-8,-6,-3,-1,2,3,5,6,7],[0,0,2,1,3,4,5,6,7,8,6,5,4,9,6]])
d = np.array([[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5]])
result = np.matmul(c,d.T)
print('After multiply c and d.T is such that :\n'+str(result))
e = np.array([[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5],[4,1,5,5,6,0,-4,-2,-1,6,6,7,8,9,0]])
result = np.matmul(c,e.transpose())
print('After multiply c and e.traspose is such that :\n'+str(result))

g = np.array([[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5],[1,2,3,4,5,6,7,2,3,4,5,6,8,9,0],[4,6,3,2,1,-9,-7,0,6,4,0,0,1,-2,3],
              [4,1,5,5,6,0,-4,-2,-1,6,6,7,8,9,0]])
result = np.matmul(c,g.transpose())
print('After multiply c and g.traspose is such that :\n'+str(result))

h = np.array([[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5],[1,2,3,4,5,6,7,2,3,4,5,6,8,9,0],[4,6,3,2,1,-9,-7,0,6,4,0,0,1,-2,3],
              [4,1,5,5,6,0,-4,-2,-1,6,6,7,8,9,0],[0,0,7,0,5,4,3,9,0,1,0,0,8,-9,-2],[1,2,3,4,5,6,7,8,9,0,0,9,8,4,3]])
result = np.matmul(c,h.transpose())
print('After multiply c and h.traspose is such that :\n'+str(result))

After multiply c and d.T is such that :
[[440]
 [158]
 [132]
 [355]
 [336]
 [300]
 [ 39]
 [218]
 [383]
 [310]
 [151]
 [358]
 [354]
 [-53]
 [369]]
After multiply c and e.traspose is such that :
[[440 158]
 [158 390]
 [132  66]
 [355 193]
 [336 124]
 [300 277]
 [ 39  89]
 [218 107]
 [383 211]
 [310 148]
 [151  24]
 [358 181]
 [354 197]
 [-53 245]
 [369 226]]
After multiply c and g.traspose is such that :
[[440 300  39 158]
 [158 277  89 390]
 [132 113  17  66]
 [355 294  20 193]
 [336 210 109 124]
 [300 375 -41 277]
 [ 39 -41 262  89]
 [218 174  17 107]
 [383 358  10 211]
 [310 284 -51 148]
 [151  96  -7  24]
 [358 337  -2 181]
 [354 346  -5 197]
 [-53  47 168 245]
 [369 322  18 226]]
After multiply c and h.traspose is such that :
[[440 300  39 158 151 358]
 [158 277  89 390  24 181]
 [132 113  17  66  38 175]
 [355 294  20 193 154 312]
 [336 210 109 124 156 255]
 [300 375 -41 277  96 337]
 [ 39 -41 262  89  -7  -2]
 [218 174  17 107 122 213]
 [383 358  10 211 151 446]
 [310 284 -51 148 

# b.) Statistic

In [55]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print('=> the minimum value of a is such that :\n',np.min(a,axis=-1))
print('=> the minimum value of a is such that :\n',np.min(a,axis=0))
print('=> the minimum value of a is such that :\n',np.min(a,axis=1))

print('=> the maximum value of a is such that :\n',np.max(a,axis=-1))
print('=> the maximum value of a is such that :\n',np.max(a,axis=0))

print('=> the average value of a is such that :\n',np.average(a,axis=0))
print('=> the average value of a is such that :\n',np.average(a,axis=1))

summation = np.sum(a)
print(summation)
Summation = np.sum(a,axis = 0)
print('==> the summation of elements in the matrix a is such that :')
print(Summation)

=> the minimum value of a is such that :
 [[1]
 [4]
 [7]]
=> the minimum value of a is such that :
 [[1 2 3]]
=> the minimum value of a is such that :
 [[1]
 [4]
 [7]]
=> the maximum value of a is such that :
 [[3]
 [6]
 [9]]
=> the maximum value of a is such that :
 [[7 8 9]]
=> the average value of a is such that :
 [[4. 5. 6.]]
=> the average value of a is such that :
 [[2.]
 [5.]
 [8.]]
45
==> the summation of elements in the matrix a is such that :
[[12 15 18]]


# c.) Reorganizing array

In [56]:
before = np.matrix([[1,2,3,4],[5,6,7,8]])
print('matrix before :\n'+str(before))

after = before.reshape((8,1))
print('matrix after :\n'+str(after))

after = before.reshape((4,2))
print('matrix after :\n'+str(after))

matrix before :
[[1 2 3 4]
 [5 6 7 8]]
matrix after :
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
matrix after :
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [57]:
# Vertically Stacking Vectors
print('vertical stack :')
v1 = np.matrix([1,2,3,4])
v2 = np.matrix([5,6,7,8])
x = np.vstack([v1,v2])
print(x)
print('\n',end='')
y = np.vstack([v1,v2,v1,v2])
print(y)

# Horizontal Stack
print('horizontal stack :')
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
z = np.hstack((h1,h2))
print(z)

vertical stack :
[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
horizontal stack :
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


# d.) Miscellaneous

In [58]:
# load data from file
file = np.genfromtxt('data2.txt',delimiter=',')
file.astype('int32')
print(file)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  38.  40.  78.  90.
   9.  87.  56.  78.  99. 900. 987. 865. 453. 100.]


# e.) Boolean Masking and Advance Indexing

In [59]:
print('==> The element that are bigger than 50 are such that :\n'+str(file>50)) 
print('\n==> The element that are smaller than 50 are such that :\n',end=''+str(file<50))
# this syntax is used to show the value(true and false if any element in matrix verificate.)
w = file[file<10]
x = file[file>100]
y = file[file<50]
z = file[file>10]
print('==> the elements that are smaller than 10 are such that :\n',w)
print('\n==> the elements that are bigger than 100 are such that :\n',x)
print('==> the elements that are smaller than 50 are such that :\n',y)
print('==> the elements that are bigger than 10 are such that :\n',z)

==> The element that are bigger than 50 are such that :
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True  True False  True  True  True  True  True
  True  True  True  True]

==> The element that are smaller than 50 are such that :
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False  True False False False False False
 False False False False]==> the elements that are smaller than 10 are such that :
 [1. 2. 3. 4. 5. 6. 7. 8. 9. 9.]

==> the elements that are bigger than 100 are such that :
 [900. 987. 865. 453.]
==> the elements that are smaller than 50 are such that :
 [ 1.  2.  3.  4.  5

In [60]:
x = np.all(file>50,axis = 0)
print(x)

y = (~(file>50)&(file<100))
print(y)
# ~ = not. For example a & b = true then, ~(a & b) = false.
z = (~(file<50))
print(z)    

False
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False  True False False False False False
 False False False False]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True  True False  True  True  True  True  True
  True  True  True  True]


# f.) Index with a List

In [61]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [62]:
y = np.array([1,2,3,4,5])
for i in range(1,6):
    if i==1:
        x = np.array([i,i+1,i+2,i+3,i+4])
    elif i==2:
        x = np.array([i+4,i+5,i+6,i+7,i+8])
    elif i==3:
        x = np.array([i+8,i+9,i+10,i+11,i+12])
    elif i==4:
        x = np.array([i+12,i+13,i+14,i+15,i+16])
    elif i==5:
        x = np.array([i+16,i+17,i+18,i+19,i+20])
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
