### Commonly basic method

<font color = yellow>I.) NumPy provides a wide range of functions and methods for working with arrays and matrices. Here are some of the most commonly used methods in NumPy:</font>

+ <font color=yellow>ndarray.shape</font>: returns a tuple representing the dimensions of the array.
+ <font color=yellow>ndarray.ndim</font>: returns the number of dimensions of the array.
+ <font color=yellow>ndarray.size</font>: returns the number of elements in the array.
+ <font color=yellow>ndarray.dtype</font>: returns the data type of the array elements.
+ <font color=yellow>ndarray.itemsize</font>: returns the size in bytes of each element of the array.
+ <font color=yellow>ndarray.astype()</font>: returns a copy of the array with a new data type.
+ <font color=yellow>ndarray.flatten()</font>: returns a flattened version of the array.
+ <font color=yellow>ndarray.reshape()</font>: returns a new array with a specified shape.
+ <font color=yellow>ndarray.transpose()</font>: returns a new array with the axes transposed.
+ <font color=yellow>ndarray.sum()</font>: returns the sum of the elements in the array.
+ <font color=yellow>ndarray.mean()</font>: returns the mean of the elements in the array.
+ <font color=yellow>ndarray.max()</font>: returns the maximum element in the array.
+ <font color=yellow>ndarray.min()</font>: returns the minimum element in the array.
+ <font color=yellow>ndarray.argsort()</font>: returns the indices that would sort the array.
+ <font color=yellow>ndarray.sort()</font>: sorts the array in place.
+ <font color=yellow>ndarray.clip()</font>: clips the values in the array to a specified range.
+ <font color=yellow>np.concatenate()</font>: concatenates two or more arrays along a specified axis.
+ <font color=yellow>np.vstack()</font>: stacks arrays vertically (i.e., row-wise).
+ <font color=yellow>np.hstack()</font>: stacks arrays horizontally (i.e., column-wise).

In [1]:
import numpy as np

# create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# shape
print(arr.shape)    # prints (2, 3)

# ndim
print(arr.ndim)     # prints 2

# size
print(arr.size)     # prints 6

# dtype
print(arr.dtype)    # prints int64

# itemsize
print(arr.itemsize) # prints 8 (since int64 takes up 8 bytes)

# astype
arr_float = arr.astype(np.float64)
print(arr_float.dtype)  # prints float64

# flatten
arr_flat = arr.flatten()
print(arr_flat)     # prints [1 2 3 4 5 6]

# reshape
arr_reshaped = arr.reshape((3, 2))
print(arr_reshaped) # prints [[1 2], [3 4], [5 6]]

# transpose
arr_transposed = arr.transpose()
print(arr_transposed)  # prints [[1 4], [2 5], [3 6]]

# sum
print(arr.sum())    # prints 21

# mean
print(arr.mean())   # prints 3.5

# max
print(arr.max())    # prints 6

# min
print(arr.min())    # prints 1

# argsort
arr_sorted_indices = arr.argsort()
print(arr_sorted_indices)   # prints [[0 1 2], [0 1 2]]

# sort
arr.sort()
print(arr)          # prints [[1 2 3], [4 5 6]]

# clip
arr_clipped = arr.clip(min=3, max=5)
print(arr_clipped)  # prints [[3 3 3], [4 5 5]]

# concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_concatenated = np.concatenate((arr1, arr2))
print(arr_concatenated)     # prints [1 2 3 4 5 6]

# vstack
arr_vstacked = np.vstack((arr1, arr2))
print(arr_vstacked)        # prints [[1 2 3], [4 5 6]]

# hstack
arr_hstacked = np.hstack((arr1, arr2))
print(arr_hstacked)        # prints [1 2 3 4 5 6]


(2, 3)
2
6
int32
4
float64
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
21
3.5
6
1
[[0 1 2]
 [0 1 2]]
[[1 2 3]
 [4 5 6]]
[[3 3 3]
 [4 5 5]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


### Random method

<font color = yellow>II.) NumPy provides several random number generation functions that can be used to generate arrays of random numbers. Here are some commonly used functions:</font>

+ <font color=yellow>np.random.rand()</font>: generates an array of specified shape filled with random values from a uniform distribution over [0, 1).
+ <font color=yellow>np.random.randn()</font>: generates an array of specified shape filled with random values from a standard normal distribution (mean=0, variance=1).
+ <font color=yellow>np.random.randint()</font>: generates an array of specified shape filled with random integer values within a specified range.
+ <font color=yellow>np.random.random()</font>: generates an array of specified shape filled with random values from a uniform distribution over [0, 1).
+ <font color=yellow>np.random.choice()</font>: generates a random sample from a given 1-D array.
+ <font color=yellow>np.random.shuffle()</font>: shuffles the elements of a given array in place.
+ <font color=yellow>np.random.permutation()</font>: returns a randomly permuted sequence of a given sequence (or array).
+ <font color=yellow>np.random.seed()</font>: seeds the random number generator with a given seed value

In [2]:
import numpy as np

# generate a 1D array of random values from a uniform distribution over [0, 1)
arr1 = np.random.rand(5)
print(arr1)

# generate a 2D array of random values from a standard normal distribution
arr2 = np.random.randn(2, 3)
print(arr2)

# generate a 1D array of random integer values within the range [0, 10)
arr3 = np.random.randint(0, 10, size=5)
print(arr3)

# generate a 1D array of random values from a uniform distribution over [0, 1)
arr4 = np.random.random(5)
print(arr4)

# generate a random sample of size 3 from a given 1D array
arr5 = np.array([1, 2, 3, 4, 5])
rand_sample = np.random.choice(arr5, size=3, replace=False)
print(rand_sample)

# shuffle the elements of a given 1D array
arr6 = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr6)
print(arr6)

# generate a randomly permuted sequence of a given sequence (or array)
arr7 = np.array([1, 2, 3, 4, 5])
rand_permutation = np.random.permutation(arr7)
print(rand_permutation)

# seed the random number generator with a given seed value
np.random.seed(1234)
arr8 = np.random.rand(5)
print(arr8)


[0.65071767 0.44224448 0.41413982 0.75998079 0.51477022]
[[ 0.02923745  2.19693759 -0.59325941]
 [-0.03378616  0.40485092 -0.26885993]]
[3 0 2 5 6]
[0.20946723 0.97327881 0.62758468 0.61523499 0.29509856]
[5 3 2]
[2 3 4 1 5]
[3 2 4 1 5]
[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]


### Random Distribution

<font color = yellow>III.) Numpy.random provides various probability distributions for generating random numbers. Here are some commonly used probability distributions in numpy.random:</font>

+ <font color = yellow>Uniform Distribution</font>: np.random.uniform()
+ <font color = yellow>Normal Distribution</font>: np.random.normal()
+ <font color = yellow>Binomial Distribution</font>: np.random.binomial()
+ <font color = yellow>Poisson Distribution</font>: np.random.poisson()
+ <font color = yellow>Exponential Distribution</font>: np.random.exponential()
+ <font color = yellow>Gamma Distribution</font>: np.random.gamma()
+ <font color = yellow>Beta Distribution</font>: np.random.beta()
+ <font color = yellow>Chi-Square Distribution</font>: np.random.chisquare()
+ <font color = yellow>Student's t-Distribution</font>: np.random.standard_t()
+ <font color = yellow>F-Distribution</font>: np.random.f()

In [11]:
import numpy as np

# Uniform Distribution
uniform_dist = np.random.uniform(low=0.0, high=1.0, size=5)
print("Uniform Distribution: ", uniform_dist)

# Normal Distribution
normal_dist = np.random.normal(loc=0.0, scale=1.0, size=5)
print("Normal Distribution: ", normal_dist)

# Binomial Distribution
binomial_dist = np.random.binomial(n=10, p=0.5, size=5)
print("Binomial Distribution: ", binomial_dist)

# Poisson Distribution
poisson_dist = np.random.poisson(lam=5, size=5)
print("Poisson Distribution: ", poisson_dist)

# Exponential Distribution
exponential_dist = np.random.exponential(scale=1.0, size=5)
print("Exponential Distribution: ", exponential_dist)

# Gamma Distribution
gamma_dist = np.random.gamma(shape=1, scale=1.0, size=5)
print("Gamma Distribution: ", gamma_dist)

# Beta Distribution
beta_dist = np.random.beta(a=1, b=1, size=5)
print("Beta Distribution: ", beta_dist)

# Chi-Square Distribution
chisquare_dist = np.random.chisquare(df=2, size=5)
print("Chi-Square Distribution: ", chisquare_dist)

# Student's t-Distribution
t_dist = np.random.standard_t(df=5, size=5)
print("t-Distribution: ", t_dist)

# F-Distribution
#f_dist = np.random.f(dfn=2, dfd=10, size=5)
f_dist = np.random.f(2,10,5)
print("F-Distribution: ",f_dist)

Uniform Distribution:  [0.43696317 0.68477821 0.82071414 0.18124722 0.41572862]
Normal Distribution:  [-1.32019909  0.96369394 -1.12131155 -0.50908975 -0.38937647]
Binomial Distribution:  [5 7 3 5 6]
Poisson Distribution:  [5 5 6 5 7]
Exponential Distribution:  [0.67160901 3.39800564 1.85887684 0.32985365 3.97094155]
Gamma Distribution:  [0.13394575 0.10521809 0.12234781 0.2515072  0.11107539]
Beta Distribution:  [0.86466657 0.87534531 0.49159747 0.44240394 0.66877668]
Chi-Square Distribution:  [2.55483053 0.61767639 0.20392974 0.04356255 0.66301513]
t-Distribution:  [ 0.11788556  0.79454661 -1.50569639 -1.01362225  0.29621542]
F-Distribution:  [0.28445283 0.4698237  0.89230963 0.1158532  0.28222071]


### Linear Algebra Function

<font color = yellow>IV.) Numpy provides a wide range of linear algebra functions for performing operations on arrays and matrices. Here are some commonly used linear algebra functions in numpy:</font>

+ <font color = yellow>Dot Product</font>: np.dot()
+ <font color = yellow>Matrix Multiplication</font>: np.matmul()
+ <font color = yellow>Transpose</font>: np.transpose()
+ <font color = yellow>Inverse</font>: np.linalg.inv()
+ <font color = yellow>Determinant</font>: np.linalg.det()
+ <font color = yellow>Eigenvalues and Eigenvectors</font>: np.linalg.eig()
+ <font color = yellow>Singular Value Decomposition</font>: np.linalg.svd()
+ <font color = yellow>QR Factorization</font>: np.linalg.qr()

In [15]:
import numpy as np

# Dot Product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot Product: ", dot_product)

# Matrix Multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_multiplication = np.matmul(matrix_a, matrix_b)
print("Matrix Multiplication: ", matrix_multiplication)

# Transpose
matrix = np.array([[1, 2], [3, 4]])
transpose = np.transpose(matrix)
print("Transpose: ", transpose)

# Inverse
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)
print("Inverse: ", inverse)

# Determinant
matrix = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(matrix)
print("Determinant: ", determinant)

# Eigenvalues and Eigenvectors
matrix = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)

# Singular Value Decomposition
matrix = np.array([[1, 2], [3, 4]])
U, s, V = np.linalg.svd(matrix)
print("U: ", U)
print("s: ", s)
print("V: ", V)

# QR Factorization
matrix = np.array([[1, 2], [3, 4]])
Q, R = np.linalg.qr(matrix)
print("Q: ", Q)
print("R: ", R)

Dot Product:  32
Matrix Multiplication:  [[19 22]
 [43 50]]
Transpose:  [[1 3]
 [2 4]]
Inverse:  [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant:  -2.0000000000000004
Eigenvalues:  [-0.37228132  5.37228132]
Eigenvectors:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
U:  [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
s:  [5.4649857  0.36596619]
V:  [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
Q:  [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:  [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


### Universal function

<Font color = yellow>V.) A ufunc (Universal Functions) in NumPy is a function that operates element-wise on ndarrays. ufuncs are important for performing fast element-wise operations, such as arithmetic operations, bitwise operations, and comparison operations on large arrays. NumPy provides a wide range of built-in ufuncs, including:</font>

+ <Font color = yellow>Arithmetic operations</font>: $ add(), subtract(), multiply(), divide(), power(), mod(), etc.$
+ <Font color = yellow>Trigonometric functions</font>: $ sin(), cos(), tan(), arcsin(), arccos(), arctan(), etc.$
+ <Font color = yellow>Exponential functions</font>: $exp(), exp2(), log(), log10(), log2(), etc.$
+ <Font color = yellow>Comparison operations</font>: $equal(), not_equal(), greater(), greater_equal(), less(), less_equal(), etc.$
+ <Font color = yellow>Bitwise operations</font>: $bitwise_and(), bitwise_or(), bitwise_xor(), invert(), etc.$
+ <Font color = yellow>Reduction operations</font>: $sum(), prod(), mean(), std(), var(), min(), max(), etc.$<br>
Here are some examples of using ufuncs in NumPy:

In [16]:
import numpy as np

# Arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition = np.add(a, b)
print("Addition: ", addition)

# Trigonometric functions
theta = np.linspace(0, np.pi, 3)
sine = np.sin(theta)
print("Sine: ", sine)

# Exponential functions
x = np.array([1, 2, 3])
exponential = np.exp(x)
print("Exponential: ", exponential)

# Comparison operations
x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
greater = np.greater(x, y)
print("Greater: ", greater)

# Bitwise operations
a = np.array([1, 2, 3], dtype=np.uint8)
b = np.array([4, 5, 6], dtype=np.uint8)
bitwise_and = np.bitwise_and(a, b)
print("Bitwise And: ", bitwise_and)

# Reduction operations
a = np.array([1, 2, 3])
sum_a = np.sum(a)
print("Sum: ", sum_a)

Addition:  [5 7 9]
Sine:  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponential:  [ 2.71828183  7.3890561  20.08553692]
Greater:  [False False  True]
Bitwise And:  [0 0 2]
Sum:  6
